#!/bin/bash
#| -*- mode: scheme -*-
dir=$(dirname "$0")
exec scheme-env run sagittarius@0.9.11 -l $dir/lib -- "$0" "$@"
|#
(import (rnrs)
	(climate)
	(text json)
	(json pp)
	(json jwt))

(define json-cli
  (climate json-cli
   (prefab jwt-command)
   (format "Format JSON command" json-pp
    (arguments
     ((input "JSON input to be formatted. Can be stdin, file or JSON string"))))))

(define (main args)
  (let ((result (execute-climate json-cli (cdr args))))
    (display (result-value result)) (newline)
    (if (result-success? result)
	(exit 0))
	(exit -1)))
	   
